### ISSUE TITLE
Using less common codecs like DNxHD and ProRes

### ISSUE THREAD

**Issue by nalsai** [flathub/org.gnome.gitlab.YaLTeR.Identity#6]
Hey, I'm not sure where this problem should be reported, but I'm trying to compare DNxHD/DNxHR and ProRes files. The Identity flatpak just keeps on showing the loading screen.
They can be decoded by gstreamer libav. With ffmpeg-full installed ffmpeg supports them (the stripped down version in the runtime doesn't) but gstreamer inside the flatpak only has the few decoders included directly in the runtime ffmpeg available.

See 
```
flatpak --command=bash run org.gnome.gitlab.YaLTeR.Identity
ffmpeg -decoders | less   # with ffmpeg-full installed, it has "VFS..D dnxhd                VC3/DNxHD"
gst-inspect-1.0           # missing "libav:  avdec_dnxhd: libav VC3/DNxHD decoder"
```

**Comment by YaLTeR** [comment]
Hey, hmm, that's interesting that it keeps showing the loading screen. Could you attach some sample files that do this?

I'm not really sure how gstreamer detects ffmpeg decoders and why it doesn't see ffmpeg-full ones in this case. I can definitely add ffmpeg-full to Identity's manifest if it will help. FWIW, Video Trimmer does have ffmpeg-full in the manifest, and yet dnxhd does not seem to appear in its `ffmpeg -decoders | grep -i dnxhd` (it does appear in my Fedora 38 toolbox).

**Comment by nalsai** [comment]
It always keeps showing the loading screen whenever something doesn't work.
Identity already has ffmpeg-full in the manifest, otherwise `ffmpeg -decoders` would be shorter. But you're right, it doesn't have dnxhd. I must've accidentally ran it on the wrong build. Sorry for the confusion. gstreamer does correctly detect the ffmpeg-full decoders, it only doesn't detect them from a bundled ffmpeg build.


Here's a DNxHR example file https://nalsai.s-ul.eu/S2rzhWDC if you still want it. In Video Trimmer it just shows "Could Not Load Video Track" and only plays the audio.

**Comment by YaLTeR** [comment]
Thanks, I'll check out the file. Ideally it should not stay spinning indefinitely and show something like what video trimmer says.

**Comment by YaLTeR** [comment]
Made an issue for the spinner here: https://gitlab.gnome.org/YaLTeR/identity/-/issues/46
